MODULE LINKED_LIST
    
    IMPLICIT NONE
    
    INTEGER :: LIST_SIZE
    INTEGER, DIMENSION(0:49999) :: LIST
    
CONTAINS

    SUBROUTINE LIST_CLEAR_()
        INTEGER :: I
        LIST_SIZE = 0
    END SUBROUTINE
    
    SUBROUTINE LIST_INSERT_(VALUE)
        INTEGER, INTENT(IN) :: VALUE
        LIST(LIST_SIZE) = VALUE
        LIST_SIZE = LIST_SIZE + 1
    END SUBROUTINE
    
END MODULE