    
    SUBROUTINE HEAP_CLEAR__()
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'HEAP_CLEAR__':: RETINA_SOLVER
        USE HEAP_MOD
        CALL HEAP_CLEAR_()
    END SUBROUTINE
    
    SUBROUTINE HEAP_INSERT__(VALUE)
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'HEAP_INSERT__':: RETINA_SOLVER
        USE HEAP_MOD
        INTEGER, INTENT(IN) :: VALUE
        CALL HEAP_INSERT_(VALUE)
    END SUBROUTINE

    SUBROUTINE HEAP_PRINT__()
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'HEAP_PRINT__':: RETINA_SOLVER
        USE HEAP_MOD
        CALL HEAP_PRINT_()
    END SUBROUTINE
    