    
    
    SUBROUTINE RB_INIT__(SIZE)
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'RB_INIT__':: RETINA_SOLVER
        USE RED_BLACK_TREE
        INTEGER, INTENT(IN) :: SIZE        
        CALL RB_INIT_(SIZE)
    END SUBROUTINE
    
    SUBROUTINE RB_INSERT__(ID, VALUE)
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'RB_INSERT__':: RETINA_SOLVER
        USE RED_BLACK_TREE
        INTEGER, INTENT(IN) :: ID, VALUE        
        CALL RB_INSERT_(ID, VALUE)
    END SUBROUTINE
    
    SUBROUTINE RB_DELETE__(ID)
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'RB_DELETE__':: RETINA_SOLVER
        USE RED_BLACK_TREE
        INTEGER, INTENT(IN) :: ID
        CALL RB_DELETE_(ID)
    END SUBROUTINE
    
    FUNCTION RB_MAX__() RESULT(ANS)
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'RB_MAX__':: RETINA_SOLVER
        USE RED_BLACK_TREE
        INTEGER :: ANS
        ANS = RB_TREE_MAX_()
    END FUNCTION
    
    SUBROUTINE RB_PRINT__()
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'RB_PRINT__':: RETINA_SOLVER
        USE RED_BLACK_TREE
        INTEGER :: I, SIZE
        SIZE = RB_SIZE
        WRITE (*,*) 'PRINTING:'
        WRITE (*,*) 'ROOT = ', ROOT
        DO I = 0, SIZE - 1
            WRITE (*, 10) I, PARENT(I), LEFT(I), RIGHT(I), COLOR(I), POTENTIAL(I)
        END DO            
10      FORMAT(I5,':', I5, I5, I5, L5, I5)        
    END SUBROUTINE
    
    SUBROUTINE RB_ORDERED_PRINT__()
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'RB_ORDERED_PRINT__':: RETINA_SOLVER
        USE RED_BLACK_TREE
        WRITE (*,*) 'OREDERD PRINTING:'
        WRITE (*,*) 'ROOT = ', ROOT
        IF (RB_SIZE .GT. 0) THEN
            CALL RB_ORDERED_PRINT_(ROOT)
        END IF
    END SUBROUTINE
    
    SUBROUTINE RB_FINALIZE__()
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'RB_FINALIZE__':: RETINA_SOLVER
        USE RED_BLACK_TREE
        CALL RB_FINALIZE_()
    END SUBROUTINE    