!****************************************************************************************************************!
!*                                                                                                              *!    
!*                                      NESTED FACTORIZATION PRECONDITIONER                                     *!
!*                                                                                                              *!    
!*                                                                                                              *!    
!****************************************************************************************************************!

    SUBROUTINE NF_CREATE__(LINE, PLANE, CONV_CV_SIZE, W_SIZE, CON_SIZE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_W, NF_FLOW_L, NF_FLOW_M, NF_FLOW_N, NF_D_TEMP, NF_TEMP_MATRIX, NF_C2W, NF_W2C, NF_W, NF_W_TEMP, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_W_CONNECTIVITY, NF_W_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS, NF_N_CONNECTIVITY, NF_N_ROW_STARTS, DOF_WELL_CONNECTIVITY, DOF_WELL_ROW_STARTS, WELL_DOF_CONNECTIVITY, WELL_DOF_ROW_STARTS)        
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'NF_CREATE__':: RETINA_SOLVER        
        USE OMP_LIB
        INTEGER, INTENT(IN) :: CONV_CV_SIZE, W_SIZE, CON_SIZE, LINE, PLANE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L, NF_D_TEMP, NF_TEMP_MATRIX
        DOUBLE PRECISION, DIMENSION(0:9 * NF_V_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_V
        DOUBLE PRECISION, DIMENSION(0:9 * NF_W_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_W
        DOUBLE PRECISION, DIMENSION(0:9 * NF_M_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_M
        DOUBLE PRECISION, DIMENSION(0:9 * NF_N_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_N
        
        INTEGER, DIMENSION(0:NF_V_CON_SIZE - 1), INTENT(IN) :: NF_V_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_W_CON_SIZE - 1), INTENT(IN) :: NF_W_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_M_CON_SIZE - 1), INTENT(IN) :: NF_M_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_N_CON_SIZE - 1), INTENT(IN) :: NF_N_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: NF_V_ROW_STARTS, NF_W_ROW_STARTS, NF_M_ROW_STARTS, NF_N_ROW_STARTS
        
        DOUBLE PRECISION, DIMENSION(0:9 * CON_SIZE - 1), INTENT(INOUT) :: NF_C2W, NF_W2C
        DOUBLE PRECISION, DIMENSION(0:9 * W_SIZE - 1), INTENT(INOUT) :: NF_W, NF_W_TEMP
        INTEGER, DIMENSION(0:CON_SIZE - 1), INTENT(IN) :: DOF_WELL_CONNECTIVITY, WELL_DOF_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: DOF_WELL_ROW_STARTS
        INTEGER, DIMENSION(0:W_SIZE), INTENT(IN) :: WELL_DOF_ROW_STARTS
        
        CALL CREATE_NF_WELL_(CONV_CV_SIZE, W_SIZE, CON_SIZE, NF_FLOW_D, NF_W, NF_W2C, NF_C2W, NF_W_TEMP, DOF_WELL_CONNECTIVITY, DOF_WELL_ROW_STARTS, WELL_DOF_CONNECTIVITY, WELL_DOF_ROW_STARTS)
        CALL CREATE_NF_3D_(0, CONV_CV_SIZE - 1, LINE, PLANE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_W, NF_FLOW_L, NF_FLOW_M, NF_FLOW_N, NF_D_TEMP, NF_TEMP_MATRIX, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_W_CONNECTIVITY, NF_W_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS, NF_N_CONNECTIVITY, NF_N_ROW_STARTS)
    END SUBROUTINE

    SUBROUTINE NF_SOLVE__(X, B, LINE, PLANE, CONV_CV_SIZE, W_SIZE, CON_SIZE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_W, NF_FLOW_L, NF_FLOW_M, NF_FLOW_N, NF_TEMP_VECTOR1, NF_TEMP_VECTOR2, NF_C2W, NF_W2C, NF_W, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_W_CONNECTIVITY, NF_W_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS, NF_N_CONNECTIVITY, NF_N_ROW_STARTS, DOF_WELL_CONNECTIVITY, DOF_WELL_ROW_STARTS, WELL_DOF_CONNECTIVITY, WELL_DOF_ROW_STARTS)        
        !DEC$ ATTRIBUTES DLLEXPORT, ALIAS : 'NF_SOLVE__':: RETINA_SOLVER        
        INTEGER, INTENT(IN) :: CONV_CV_SIZE, W_SIZE, CON_SIZE, LINE, PLANE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L
        DOUBLE PRECISION, DIMENSION(0:9 * NF_V_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_V
        DOUBLE PRECISION, DIMENSION(0:9 * NF_W_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_W
        DOUBLE PRECISION, DIMENSION(0:9 * NF_M_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_M
        DOUBLE PRECISION, DIMENSION(0:9 * NF_N_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_N
        
        DOUBLE PRECISION, DIMENSION(0:3 * CONV_CV_SIZE - 1), INTENT(INOUT) :: NF_TEMP_VECTOR1, NF_TEMP_VECTOR2
        DOUBLE PRECISION, DIMENSION(0:3 * (CONV_CV_SIZE + W_SIZE) - 1), INTENT(INOUT) :: X
        DOUBLE PRECISION, DIMENSION(0:3 * (CONV_CV_SIZE + W_SIZE) - 1), INTENT(IN) :: B
        
        INTEGER, DIMENSION(0:NF_V_CON_SIZE - 1), INTENT(IN) :: NF_V_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_W_CON_SIZE - 1), INTENT(IN) :: NF_W_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_M_CON_SIZE - 1), INTENT(IN) :: NF_M_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_N_CON_SIZE - 1), INTENT(IN) :: NF_N_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: NF_V_ROW_STARTS, NF_W_ROW_STARTS, NF_M_ROW_STARTS, NF_N_ROW_STARTS
        
        DOUBLE PRECISION, DIMENSION(0:9 * CON_SIZE - 1), INTENT(INOUT) :: NF_C2W, NF_W2C
        DOUBLE PRECISION, DIMENSION(0:9 * W_SIZE - 1), INTENT(INOUT) :: NF_W
        INTEGER, DIMENSION(0:CON_SIZE - 1), INTENT(IN) :: DOF_WELL_CONNECTIVITY, WELL_DOF_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: DOF_WELL_ROW_STARTS
        INTEGER, DIMENSION(0:W_SIZE), INTENT(IN) :: WELL_DOF_ROW_STARTS
        
        INTEGER :: I, II, ROW, J, J_INDEX, C0, SIZE
        
        SIZE = CONV_CV_SIZE + W_SIZE
        
        !DEC$ SIMD
        DO ROW = 0, W_SIZE - 1
            C0 = 3 * ROW
            DO II = 0, 2
                X(C0 + II) = 0.D0
            END DO
        END DO
        
        !DEC$ SIMD
        DO ROW = W_SIZE, SIZE - 1
            C0 = 3 * ROW
            DO II = 0, 2
                X(C0 + II) = B(C0 + II)
            END DO
        END DO
        
        DO I = 0, W_SIZE - 1
            CALL MULT_MV__(NF_W(9 * I:9 * I + 8), B(3 * I:3 * I + 2), X(3 * I:3 * I +2), 1.D0, 0, 0)
        END DO
        DO ROW = 0, CONV_CV_SIZE - 1
            DO J_INDEX = DOF_WELL_ROW_STARTS(ROW), DOF_WELL_ROW_STARTS(ROW + 1) - 1
                J = DOF_WELL_CONNECTIVITY(J_INDEX)
                CALL MULT_MV__(NF_C2W(9 * J_INDEX:9 * J_INDEX + 8), X(3 * J:3 * J + 2), X(3 * (W_SIZE + ROW):3 * (W_SIZE + ROW) + 2), -1.D0, 0, 0)
            END DO
        END DO
        CALL NF_3D_SOLVE_VECTOR_(X(3 * W_SIZE:3 * SIZE - 1), 0, CONV_CV_SIZE - 1, LINE, PLANE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_W, NF_FLOW_L, NF_FLOW_M, NF_FLOW_N, NF_TEMP_VECTOR1, NF_TEMP_VECTOR2, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_W_CONNECTIVITY, NF_W_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS, NF_N_CONNECTIVITY, NF_N_ROW_STARTS)        

        CALL CLEAR_RANGE_VECTOR__(0, W_SIZE - 1, W_SIZE, NF_TEMP_VECTOR1(0:3 * W_SIZE - 1))
        DO ROW = 0, W_SIZE - 1
            DO J_INDEX = WELL_DOF_ROW_STARTS(ROW), WELL_DOF_ROW_STARTS(ROW + 1) - 1                
                J = WELL_DOF_CONNECTIVITY(J_INDEX)
                CALL MULT_MV__(NF_W2C(9 * J_INDEX:9 * J_INDEX + 8), X(3 * (W_SIZE + J):3 * (W_SIZE + J) + 2), NF_TEMP_VECTOR1(3 * ROW:3 * ROW + 2), 1.D0, 0, 0)
            END DO
        END DO
        DO I = 0, W_SIZE - 1
            CALL MULT_MV__(NF_W(9 * I: 9 * I + 8), NF_TEMP_VECTOR1(3 * I:3 * I + 2), X(3 * I:3 * I + 2), -1.D0, 0, 0)
        END DO
    END SUBROUTINE

    SUBROUTINE CREATE_DI_(NF_FLOW_D, NF_D_TEMP)    
        DOUBLE PRECISION, DIMENSION(0:8), INTENT(IN) :: NF_D_TEMP
        DOUBLE PRECISION, DIMENSION(0:8), INTENT(INOUT) :: NF_FLOW_D
        INTEGER :: II
        !DEC$ SIMD
        DO II = 0, 8
            NF_FLOW_D(II) = NF_D_TEMP(II)
        END DO
        CALL INV__(NF_FLOW_D)
    END SUBROUTINE
            
    SUBROUTINE CREATE_NF_3D_(I1, I2, LINE, PLANE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_W, NF_FLOW_L, NF_FLOW_M, NF_FLOW_N, NF_D_TEMP, NF_TEMP_MATRIX, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_W_CONNECTIVITY, NF_W_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS, NF_N_CONNECTIVITY, NF_N_ROW_STARTS)
        INTEGER, INTENT(IN) :: I1, I2, LINE, PLANE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L, NF_D_TEMP, NF_TEMP_MATRIX
        DOUBLE PRECISION, DIMENSION(0:9 * NF_V_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_V
        DOUBLE PRECISION, DIMENSION(0:9 * NF_W_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_W
        DOUBLE PRECISION, DIMENSION(0:9 * NF_M_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_M
        DOUBLE PRECISION, DIMENSION(0:9 * NF_N_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_N
        
        INTEGER, DIMENSION(0:NF_V_CON_SIZE - 1), INTENT(IN) :: NF_V_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_W_CON_SIZE - 1), INTENT(IN) :: NF_W_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_M_CON_SIZE - 1), INTENT(IN) :: NF_M_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_N_CON_SIZE - 1), INTENT(IN) :: NF_N_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: NF_V_ROW_STARTS, NF_W_ROW_STARTS, NF_M_ROW_STARTS, NF_N_ROW_STARTS
        INTEGER :: I, ROW, J_INDEX, J
        CALL COPY_RANGE__(0, CONV_CV_SIZE - 1, CONV_CV_SIZE, NF_FLOW_D, NF_D_TEMP)        
        DO I = I1, I2, PLANE
            IF (I .GT. I1) THEN   
                ! ROW SUM
                !CALL ROW_SUM_(I - PLANE, I - 1, NF_W_CON_SIZE, CONV_CV_SIZE, NF_W_ROW_STARTS, NF_FLOW_W, NF_D_TEMP)                          
                !CALL NF_2D_SOLVE_MATRIX_(NF_D_TEMP, I - PLANE, I - 1, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_L, NF_FLOW_M, NF_TEMP_MATRIX, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS)                                                
                !DO ROW = I, I + PLANE - 1
                !    DO J_INDEX = NF_N_ROW_STARTS(ROW), NF_N_ROW_STARTS(ROW + 1) - 1                        
                !        J = NF_N_CONNECTIVITY(J_INDEX)
                !        CALL MULT_MM__(NF_FLOW_N(9 * J_INDEX:9 * J_INDEX + 8), NF_D_TEMP(9 * J:9 * J + 8), NF_D_TEMP(9 * ROW:9 * ROW + 8), -1.D0)
                !    END DO
                !END DO
                
                ! COL SUM
                CALL ROW_SUM_TRANSPOSE_(I - PLANE, I - 1, I, I + PLANE - 1, NF_N_CON_SIZE, CONV_CV_SIZE, CONV_CV_SIZE, NF_N_ROW_STARTS, NF_N_CONNECTIVITY, NF_FLOW_N, NF_D_TEMP)                                
                CALL NF_2D_SOLVE_MATRIX_TRANSPOSE_(NF_D_TEMP, I - PLANE, I - 1, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_L, NF_FLOW_M, NF_TEMP_MATRIX, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS)                
                DO ROW = I - PLANE, I - 1
                    DO J_INDEX = NF_W_ROW_STARTS(ROW), NF_W_ROW_STARTS(ROW + 1) - 1                        
                        J = NF_W_CONNECTIVITY(J_INDEX)
                        CALL MULT_MTM_TRANSPOSE__(NF_FLOW_W(9 * J_INDEX:9 * J_INDEX + 8), NF_D_TEMP(9 * ROW:9 * ROW + 8), NF_D_TEMP(9 * J:9 * J + 8), -1.D0)
                    END DO
                END DO
            END IF
            CALL CREATE_NF_2D_(I, I + PLANE - 1, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_L, NF_FLOW_M, NF_D_TEMP, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS)
        END DO
    END SUBROUTINE
    
    SUBROUTINE CREATE_NF_2D_(I1, I2, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_L, NF_FLOW_M, NF_D_TEMP, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS)
        INTEGER, INTENT(IN) :: I1, I2, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L, NF_D_TEMP
        DOUBLE PRECISION, DIMENSION(0:9 * NF_V_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_V
        DOUBLE PRECISION, DIMENSION(0:9 * NF_M_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_M
        
        INTEGER, DIMENSION(0:NF_V_CON_SIZE - 1), INTENT(IN) :: NF_V_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_M_CON_SIZE - 1), INTENT(IN) :: NF_M_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: NF_V_ROW_STARTS, NF_M_ROW_STARTS
        INTEGER :: I, ROW, J_INDEX, J
        DO I = I1, I2, LINE
            IF (I .GT. I1) THEN
                ! ROW SUM
                !CALL ROW_SUM_(I - LINE, I - 1, NF_V_CON_SIZE, CONV_CV_SIZE, NF_V_ROW_STARTS, NF_FLOW_V, NF_D_TEMP)                 
                !CALL TRI_SOLVE_MATRIX_(NF_D_TEMP, I - LINE, I - 1, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)                                            
                !DO ROW = I, I + LINE - 1
                !    DO J_INDEX = NF_M_ROW_STARTS(ROW), NF_M_ROW_STARTS(ROW + 1) - 1                        
                !        J = NF_M_CONNECTIVITY(J_INDEX)
                !        CALL MULT_MM__(NF_FLOW_M(9 * J_INDEX:9 * J_INDEX + 8), NF_D_TEMP(9 * J:9 * J + 8), NF_D_TEMP(9 * ROW:9 * ROW + 8), -1.D0)
                !    END DO
                !END DO                
                
                ! COL SUM
                CALL ROW_SUM_TRANSPOSE_(I - LINE, I - 1, I, I + LINE - 1, NF_M_CON_SIZE, CONV_CV_SIZE, CONV_CV_SIZE, NF_M_ROW_STARTS, NF_M_CONNECTIVITY, NF_FLOW_M, NF_D_TEMP)
                CALL TRI_SOLVE_MATRIX_TRANSPOSE_(NF_D_TEMP, I - LINE, I - 1, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)                                                            
                DO ROW = I - LINE, I - 1
                    DO J_INDEX = NF_V_ROW_STARTS(ROW), NF_V_ROW_STARTS(ROW + 1) - 1                        
                        J = NF_V_CONNECTIVITY(J_INDEX)
                        CALL MULT_MTM_TRANSPOSE__(NF_FLOW_V(9 * J_INDEX:9 * J_INDEX + 8), NF_D_TEMP(9 * ROW:9 * ROW + 8), NF_D_TEMP(9 * J:9 * J + 8), -1.D0)
                    END DO
                END DO
            END IF
            CALL CREATE_NF_1D_(I, I + LINE - 1, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L, NF_D_TEMP)            
        END DO
    END SUBROUTINE

    SUBROUTINE CREATE_NF_1D_(I1, I2, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L, NF_D_TEMP)
        INTEGER, INTENT(IN) :: I1, I2, CONV_CV_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: NF_FLOW_D, NF_D_TEMP, NF_FLOW_U, NF_FLOW_L
        INTEGER :: I

        CALL CREATE_DI_(NF_FLOW_D(9 * I1:9 * I1 + 8), NF_D_TEMP(9 * I1:9 * I1 + 8))
        CALL COPY_MULT_MM__(NF_FLOW_D(9 * I1:9 * I1 + 8), NF_FLOW_U(9 * I1:9 * I1 + 8), NF_FLOW_U(9 * I1:9 * I1 + 8), 1.D0)        
        
        DO I = I1 + 1, I2 - 1
            CALL MULT_MM__(NF_FLOW_L(9 * I:9 * I + 8), NF_FLOW_U(9 * (I - 1):9 * (I - 1) + 8), NF_D_TEMP(9 * I:9 * I + 8), -1.D0, 0 ,0 ,0)
            CALL CREATE_DI_(NF_FLOW_D(9 * I:9 * I + 8), NF_D_TEMP(9 * I:9 * I + 8))
            CALL COPY_MULT_MM__(NF_FLOW_D(9 * I:9 * I + 8), NF_FLOW_U(9 * I:9 * I + 8), NF_FLOW_U(9 * I:9 * I + 8), 1.D0)
        END DO        
        
        CALL MULT_MM__(NF_FLOW_L(9 * I:9 * I + 8), NF_FLOW_U(9 * (I - 1):9 * (I - 1) + 8), NF_D_TEMP(9 * I:9 * I + 8), -1.D0, 0 ,0 ,0)
        CALL CREATE_DI_(NF_FLOW_D(9 * I:9 * I + 8), NF_D_TEMP(9 * I:9 * I + 8))
    END SUBROUTINE    
    
    SUBROUTINE CREATE_NF_WELL_(CONV_CV_SIZE, W_SIZE, CON_SIZE, NF_FLOW_D, NF_W, NF_W2C, NF_C2W, NF_W_TEMP, DOF_WELL_CONNECTIVITY, DOF_WELL_ROW_STARTS, WELL_DOF_CONNECTIVITY, WELL_DOF_ROW_STARTS)
        INTEGER, INTENT(IN) :: CONV_CV_SIZE, W_SIZE, CON_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: NF_FLOW_D
        DOUBLE PRECISION, DIMENSION(0:9 * W_SIZE - 1), INTENT(INOUT) :: NF_W, NF_W_TEMP
        DOUBLE PRECISION, DIMENSION(0:9 * CON_SIZE - 1), INTENT(IN) :: NF_W2C, NF_C2W
        INTEGER, DIMENSION(0:CON_SIZE - 1), INTENT(IN) :: DOF_WELL_CONNECTIVITY, WELL_DOF_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: DOF_WELL_ROW_STARTS
        INTEGER, DIMENSION(0:W_SIZE), INTENT(IN) :: WELL_DOF_ROW_STARTS
        INTEGER :: I, ROW, C0, J, J_INDEX, INDEX
        
        DO I = 0, W_SIZE - 1
            C0 = 9 * I
            CALL INV__(NF_W(C0:C0 + 8))
        END DO        
        
        ! ROW SUM
        !CALL ROW_SUM_(0, W_SIZE - 1, CON_SIZE, W_SIZE, WELL_DOF_ROW_STARTS, NF_W2C, NF_W_TEMP)
        !DO I = 0, W_SIZE - 1
        !    CALL COPY_MULT_MM__(NF_W(9 * I:9 * I + 8), NF_W_TEMP(9 * I:9 * I + 8), NF_W_TEMP(9 * I:9 * I + 8), 1.D0)
        !END DO
        !
        !DO I = 0, W_SIZE - 1
        !    DO J_INDEX = WELL_DOF_ROW_STARTS(I), WELL_DOF_ROW_STARTS(I + 1) - 1
        !        J = WELL_DOF_CONNECTIVITY(J_INDEX)
        !        ! ASSUMING EACH CELL CONNECTS TO ONLY ONE WELL AT MOST
        !        INDEX = DOF_WELL_ROW_STARTS(J)
        !        CALL MULT_MM__(NF_C2W(9 * INDEX:9* INDEX + 8), NF_W_TEMP(9 * I:9 * I + 8), NF_FLOW_D(9 * J:9 * J + 8), -1.D0)
        !    END DO
        !END DO

        ! COL SUM
        CALL ROW_SUM_TRANSPOSE_(0, W_SIZE - 1, 0, CONV_CV_SIZE - 1, CON_SIZE, W_SIZE, CONV_CV_SIZE, DOF_WELL_ROW_STARTS, DOF_WELL_CONNECTIVITY, NF_C2W, NF_W_TEMP)
        DO I = 0, W_SIZE - 1
            CALL COPY_MULT_MTM__(NF_W(9 * I:9 * I + 8), NF_W_TEMP(9 * I:9 * I + 8), NF_W_TEMP(9 * I:9 * I + 8), 1.D0)
        END DO
        DO I = 0, W_SIZE - 1
            DO J_INDEX = WELL_DOF_ROW_STARTS(ROW), WELL_DOF_ROW_STARTS(ROW + 1) - 1
                J = WELL_DOF_CONNECTIVITY(J_INDEX)
                CALL MULT_MTM_TRANSPOSE__(NF_W2C(9 * J_INDEX:9 * J_INDEX + 8), NF_W_TEMP(9 * ROW:9 * ROW + 8), NF_FLOW_D(9 * J:9 * J + 8), -1.D0)
            END DO
        END DO
    END SUBROUTINE
    
    SUBROUTINE TRI_SOLVE_MATRIX_TRANSPOSE_(X, I1, I2, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)    
        INTEGER, INTENT(IN) :: I1, I2, CONV_CV_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(IN) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: X
        INTEGER :: I
        DO I = I1 + 1, I2
            CALL MULT_MTM__(NF_FLOW_U(9 * (I - 1):9 * (I - 1) + 8), X(9 * (I - 1):9 * (I - 1) + 8), X(9 * I:9 * I + 8), -1.D0)            
        END DO
        CALL COPY_MULT_MTM__(NF_FLOW_D(9 * I2:9 * I2 + 8), X(9 * I2:9 * I2 + 8), X(9 * I2:9 * I2 + 8), 1.D0)
        DO I = I2 - 1, I1, -1
            CALL MULT_MTM__(NF_FLOW_L(9 * (I + 1):9 * (I + 1) + 8), X(9 * (I + 1):9 * (I + 1) + 8), X(9 * I:9 * I + 8), -1.D0)
            CALL COPY_MULT_MTM__(NF_FLOW_D(9 * I:9 * I + 8), X(9 * I:9 * I + 8), X(9 * I:9 * I + 8), 1.D0)
        END DO
    END SUBROUTINE

    SUBROUTINE TRI_SOLVE_MATRIX_(X, I1, I2, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)    
        INTEGER, INTENT(IN) :: I1, I2, CONV_CV_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(IN) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: X
        INTEGER :: I
        ! TODO        
        CALL COPY_MULT_MM__(NF_FLOW_D(9 * I1:9 * I1 + 8), X(9 * I1:9 * I1 + 8), X(9 * I1:9 * I1 + 8), 1.D0)
        DO I = I1 + 1, I2
            CALL MULT_MM__(NF_FLOW_L(9 * I:9 * I + 8), X(9 * (I - 1):9 * (I - 1) + 8), X(9 * I:9 * I + 8), -1.D0, 0 ,0 ,0)
            CALL COPY_MULT_MM__(NF_FLOW_D(9 * I:9 * I + 8), X(9 * I:9 * I + 8), X(9 * I:9 * I + 8), 1.D0)
        END DO
        DO I = I2 - 1, I1, -1
            CALL MULT_MM__(NF_FLOW_U(9 * I:9 * I + 8), X(9 * (I + 1):9 * (I + 1) + 8), X(9 * I:9 * I + 8), -1.D0, 0 ,0 ,0)
        END DO
    END SUBROUTINE
    
    SUBROUTINE TRI_SOLVE_VECTOR_(X, I1, I2, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)    
        INTEGER, INTENT(IN) :: I1, I2, CONV_CV_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(IN) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L
        DOUBLE PRECISION, DIMENSION(0:3 * CONV_CV_SIZE - 1), INTENT(INOUT) :: X
        INTEGER :: I
        CALL COPY_MULT_MV__(NF_FLOW_D(9 * I1:9 * I1 + 8), X(3 * I1:3 * I1 + 2), X(3 * I1:3 * I1 + 2), 1.D0)
        DO I = I1 + 1, I2
            CALL MULT_MV__(NF_FLOW_L(9 * I:9 * I + 8), X(3 * (I - 1):3 * (I - 1) + 2), X(3 * I:3 * I + 2), -1.D0, 0, 0)
            CALL COPY_MULT_MV__(NF_FLOW_D(9 * I:9 * I + 8), X(3 * I:3 * I + 2), X(3 * I:3 * I + 2), 1.D0)            
        END DO
        DO I = I2 - 1, I1, -1
            CALL MULT_MV__(NF_FLOW_U(9 * I:9 * I + 8), X(3 * (I + 1):3 * (I + 1) + 2), X(3 * I:3 * I + 2), -1.D0, 0, 0)
        END DO
    END SUBROUTINE

    SUBROUTINE NF_3D_SOLVE_VECTOR_(X, I1, I2, LINE, PLANE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_W, NF_FLOW_L, NF_FLOW_M, NF_FLOW_N, NF_TEMP_VECTOR1, NF_TEMP_VECTOR2, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_W_CONNECTIVITY, NF_W_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS, NF_N_CONNECTIVITY, NF_N_ROW_STARTS)
        INTEGER, INTENT(IN) :: I1, I2, LINE, PLANE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_W_CON_SIZE, NF_M_CON_SIZE, NF_N_CON_sIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(IN) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L
        DOUBLE PRECISION, DIMENSION(0:3 * CONV_CV_SIZE - 1), INTENT(INOUT) :: X, NF_TEMP_VECTOR1, NF_TEMP_VECTOR2        
        DOUBLE PRECISION, DIMENSION(0:9 * NF_V_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_V
        DOUBLE PRECISION, DIMENSION(0:9 * NF_W_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_W
        DOUBLE PRECISION, DIMENSION(0:9 * NF_M_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_M
        DOUBLE PRECISION, DIMENSION(0:9 * NF_N_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_N
        
        INTEGER, DIMENSION(0:NF_V_CON_SIZE - 1), INTENT(IN) :: NF_V_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_W_CON_SIZE - 1), INTENT(IN) :: NF_W_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_M_CON_SIZE - 1), INTENT(IN) :: NF_M_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_N_CON_SIZE - 1), INTENT(IN) :: NF_N_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: NF_V_ROW_STARTS, NF_W_ROW_STARTS, NF_M_ROW_STARTS, NF_N_ROW_STARTS
        INTEGER :: I, J, J_INDEX, ROW, C0, II
        
        DO I = I1, I2, PLANE
            IF (I .GT. I1) THEN
                DO ROW = I, I + PLANE - 1
                    DO J_INDEX = NF_N_ROW_STARTS(ROW), NF_N_ROW_STARTS(ROW + 1) - 1
                        J = NF_N_CONNECTIVITY(J_INDEX)
                        CALL MULT_MV__(NF_FLOW_N(9 * J_INDEX:9 * J_INDEX + 8), X(3 * J:3 * J + 2), X(3 * ROW:3 * ROW + 2), -1.D0, 0, 0)
                    END DO
                END DO
            END IF
            CALL NF_2D_SOLVE_VECTOR_(X, I, I + PLANE - 1, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_L, NF_FLOW_M, NF_TEMP_VECTOR2, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS)
        END DO
        CALL CLEAR_RANGE_VECTOR__(I1, I2 - PLANE, CONV_CV_SIZE, NF_TEMP_VECTOR1)
        DO I = I2 - 2 * PLANE + 1, I1, -PLANE
            DO ROW = I, I + PLANE - 1
                DO J_INDEX = NF_W_ROW_STARTS(ROW), NF_W_ROW_STARTS(ROW + 1) - 1
                    J = NF_W_CONNECTIVITY(J_INDEX)
                    CALL MULT_MV__(NF_FLOW_W(9 * J_INDEX:9 * J_INDEX + 8), X(3 * J:3 * J + 2), NF_TEMP_VECTOR1(3 * ROW:3 * ROW + 2), 1.D0, 0, 0)
                END DO
            END DO
            CALL NF_2D_SOLVE_VECTOR_(NF_TEMP_VECTOR1, I, I + PLANE - 1, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_L, NF_FLOW_M, NF_TEMP_VECTOR2, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS)            
            !DEC$ SIMD
            DO ROW = I, I + PLANE - 1
                C0 = 3 * ROW
                DO II = 0, 2
                    X(C0 + II) = X(C0 + II) - NF_TEMP_VECTOR1(C0 + II)
                END DO
            END DO
        END DO
    END SUBROUTINE
    
    SUBROUTINE NF_2D_SOLVE_MATRIX_TRANSPOSE_(X, I1, I2, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_L, NF_FLOW_M, NF_TEMP_MATRIX, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS)
        INTEGER, INTENT(IN) :: I1, I2, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(IN) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: X, NF_TEMP_MATRIX        
        DOUBLE PRECISION, DIMENSION(0:9 * NF_V_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_V
        DOUBLE PRECISION, DIMENSION(0:9 * NF_M_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_M
        
        INTEGER, DIMENSION(0:NF_V_CON_SIZE - 1), INTENT(IN) :: NF_V_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_M_CON_SIZE - 1), INTENT(IN) :: NF_M_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: NF_V_ROW_STARTS, NF_M_ROW_STARTS                
        INTEGER :: I, ROW, J_INDEX, J, C0, II
        
        DO I = I1 + LINE, I2, LINE
            CALL COPY_RANGE__(I - LINE, I - 1, CONV_CV_SIZE, X, NF_TEMP_MATRIX)
            CALL TRI_SOLVE_MATRIX_TRANSPOSE_(NF_TEMP_MATRIX, I - LINE, I - 1, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)            
            DO ROW = I - LINE, I - 1
                DO J_INDEX = NF_V_ROW_STARTS(ROW), NF_V_ROW_STARTS(ROW + 1) - 1
                    J = NF_V_CONNECTIVITY(J_INDEX)
                    CALL MULT_MTM__(NF_FLOW_V(9 * J_INDEX:9 * J_INDEX + 8), NF_TEMP_MATRIX(9 * ROW:9 * ROW + 8), X(9 * J:9 * J + 8), -1.D0)
                END DO
            END DO
        END DO
        CALL TRI_SOLVE_MATRIX_TRANSPOSE_(X, I2 - LINE + 1, I2, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)
        DO I = I2 - 2 * LINE + 1, I1, -LINE
            DO ROW = I + LINE, I + 2 * LINE - 1
                DO J_INDEX = NF_M_ROW_STARTS(ROW), NF_M_ROW_STARTS(ROW + 1) - 1
                    J = NF_M_CONNECTIVITY(J_INDEX)
                    CALL MULT_MTM__(NF_FLOW_M(9 * J_INDEX:9 * J_INDEX + 8), X(9 * ROW:9 * ROW + 8), X(9 * J:9 * J + 8), -1.D0)
                END DO
            END DO
            CALL TRI_SOLVE_MATRIX_TRANSPOSE_(X, I, I + LINE - 1, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)
        END DO
    END SUBROUTINE

    SUBROUTINE NF_2D_SOLVE_MATRIX_(X, I1, I2, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_L, NF_FLOW_M, NF_TEMP_MATRIX, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS)
        INTEGER, INTENT(IN) :: I1, I2, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(IN) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(INOUT) :: X, NF_TEMP_MATRIX        
        DOUBLE PRECISION, DIMENSION(0:9 * NF_V_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_V
        DOUBLE PRECISION, DIMENSION(0:9 * NF_M_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_M
        
        INTEGER, DIMENSION(0:NF_V_CON_SIZE - 1), INTENT(IN) :: NF_V_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_M_CON_SIZE - 1), INTENT(IN) :: NF_M_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: NF_V_ROW_STARTS, NF_M_ROW_STARTS                
        INTEGER :: I, ROW, J_INDEX, J, C0, II
        
        DO I = I1, I2, LINE
            IF (I .GT. I1) THEN
                DO ROW = I, I + LINE - 1                
                    DO J_INDEX = NF_M_ROW_STARTS(ROW), NF_M_ROW_STARTS(ROW + 1) - 1                    
                        J = NF_M_CONNECTIVITY(J_INDEX)                        
                        CALL MULT_MM__(NF_FLOW_M(9 * J_INDEX:9 * J_INDEX + 8), X(9 * J:9 * J + 8), X(9 * ROW:9 * ROW + 8), -1.D0, 0 ,0 ,0)                        
                    END DO
                END DO
            END IF
            CALL TRI_SOLVE_MATRIX_(X, I, I + LINE - 1, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)
        END DO
        CALL CLEAR_RANGE_MATRIX__(I1, I2 - LINE, CONV_CV_SIZE, NF_TEMP_MATRIX)
        DO I = I2 - 2 * LINE + 1, I1, -LINE
            DO ROW = I, I + LINE - 1            
                DO J_INDEX = NF_V_ROW_STARTS(ROW), NF_V_ROW_STARTS(ROW + 1) - 1                
                    J = NF_V_CONNECTIVITY(J_INDEX)                    
                    CALL MULT_MM__(NF_FLOW_V(9 * J_INDEX:9 * J_INDEX + 8), X(9 * J:9 * J + 8), NF_TEMP_MATRIX(9 * ROW:9 * ROW + 8), 1.D0, 0 ,0 ,0)                    
                END DO
            END DO
            CALL TRI_SOLVE_MATRIX_(NF_TEMP_MATRIX, I, I + LINE - 1, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)
            !DEC$ SIMD
            DO ROW = I, I + LINE - 1
                C0 = 9 * ROW
                DO II = 0, 8
                    X(C0 + II) = X(C0 + II) - NF_TEMP_MATRIX(C0 + II)
                END DO
            END DO
        END DO
    END SUBROUTINE
    
    SUBROUTINE NF_2D_SOLVE_VECTOR_(X, I1, I2, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_V, NF_FLOW_L, NF_FLOW_M, NF_TEMP_VECTOR2, NF_V_CONNECTIVITY, NF_V_ROW_STARTS, NF_M_CONNECTIVITY, NF_M_ROW_STARTS)
        INTEGER, INTENT(IN) :: I1, I2, LINE, CONV_CV_SIZE, NF_V_CON_SIZE, NF_M_CON_SIZE
        DOUBLE PRECISION, DIMENSION(0:9 * CONV_CV_SIZE - 1), INTENT(IN) :: NF_FLOW_D, NF_FLOW_U, NF_FLOW_L
        DOUBLE PRECISION, DIMENSION(0:3 * CONV_CV_SIZE - 1), INTENT(INOUT) :: X, NF_TEMP_VECTOR2
        DOUBLE PRECISION, DIMENSION(0:9 * NF_V_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_V
        DOUBLE PRECISION, DIMENSION(0:9 * NF_M_CON_SIZE - 1), INTENT(INOUT) :: NF_FLOW_M
        
        INTEGER, DIMENSION(0:NF_V_CON_SIZE - 1), INTENT(IN) :: NF_V_CONNECTIVITY
        INTEGER, DIMENSION(0:NF_M_CON_SIZE - 1), INTENT(IN) :: NF_M_CONNECTIVITY
        INTEGER, DIMENSION(0:CONV_CV_SIZE), INTENT(IN) :: NF_V_ROW_STARTS, NF_M_ROW_STARTS

        INTEGER :: I, J, J_INDEX, ROW, C0, II
        DO I = I1, I2, LINE
            IF (I .GT. I1) THEN
                DO ROW = I, I + LINE - 1
                    DO J_INDEX = NF_M_ROW_STARTS(ROW), NF_M_ROW_STARTS(ROW + 1) - 1
                        J = NF_M_CONNECTIVITY(J_INDEX)
                        CALL MULT_MV__(NF_FLOW_M(9 * J_INDEX:9 * J_INDEX + 8), X(3 * J:3 * J + 2), X(3 * ROW:3 * ROW + 2), -1.D0, 0, 0)
                    END DO
                END DO
            END IF
            CALL TRI_SOLVE_VECTOR_(X, I, I + LINE - 1, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)
        END DO
        CALL CLEAR_RANGE_VECTOR__(I1, I2 - LINE, CONV_CV_SIZE, NF_TEMP_VECTOR2)
        DO I = I2 - 2 * LINE + 1, I1, -LINE
            DO ROW = I, I + LINE - 1
                DO J_INDEX = NF_V_ROW_STARTS(ROW), NF_V_ROW_STARTS(ROW + 1) - 1
                    J = NF_V_CONNECTIVITY(J_INDEX)
                    CALL MULT_MV__(NF_FLOW_V(9 * J_INDEX:9 * J_INDEX + 8), X(3 * J:3 * J + 2), NF_TEMP_VECTOR2(3 * ROW:3 * ROW + 2), 1.D0, 0, 0)
                END DO
            END DO
            CALL TRI_SOLVE_VECTOR_(NF_TEMP_VECTOR2, I, I + LINE - 1, CONV_CV_SIZE, NF_FLOW_D, NF_FLOW_U, NF_FLOW_L)
            !DEC$ SIMD
            DO ROW = I, I + LINE - 1
                C0 = 3 * ROW
                DO II = 0, 2
                    X(C0 + II) = X(C0 + II) - NF_TEMP_VECTOR2(C0 + II)
                END DO
            END DO
        END DO
    END SUBROUTINE
